name: x87_mobile
description: X87 IPTV Player - Mobile client for Android and iOS
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.3.0
  device_info_plus: ^11.0.0
  crypto: ^3.0.6
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  android_intent_plus: ^5.1.0
  google_fonts: ^6.2.1
  wakelock_plus: ^1.4.0
  xml: ^6.5.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
